import { UserRecord, TruckRecord } from '../types';

export const INITIAL_USERS: UserRecord[] = [
  {
    email: 'ari.imam@daya-motora.com',
    namaTransporter: 'Ari Imam (Admin Distribusi)',
    role: 'admin',
    kodeTransporter: 'ALL',
    depo: 'Karawang',
  },
  {
    email: 'admin@logistik.id',
    namaTransporter: 'Admin Logistik Pusat (Semua Vendor)',
    role: 'admin',
    kodeTransporter: 'ALL',
    depo: 'Karawang',
  },
  {
    email: 'ops.tm@logistik.id',
    namaTransporter: 'PT. Tunas Muda (TM)',
    role: 'transporter',
    kodeTransporter: 'TM',
    depo: 'Karawang',
  },
  {
    email: 'fleet.rjtm@logistik.id',
    namaTransporter: 'PT. Roda Jagat Tunas Mas (RJTM)',
    role: 'transporter',
    kodeTransporter: 'RJTM',
    depo: 'Karawang',
  },
  {
    email: 'logistik.wss@logistik.id',
    namaTransporter: 'PT. Wahana Sumber Sakti (WSS)',
    role: 'transporter',
    kodeTransporter: 'WSS',
    depo: 'Karawang',
  },
  {
    email: 'armada.sbr@logistik.id',
    namaTransporter: 'PT. Sari Bumi Raya (SBR)',
    role: 'transporter',
    kodeTransporter: 'SBR',
    depo: 'Karawang',
  },
];

export const INITIAL_TRUCKS: TruckRecord[] = [
  // Transporter TM (PT. Tunas Muda)
  {
    id: 'TRK-101',
    transporter: 'TM',
    depo: 'Karawang',
    nomorPolisi: 'B 9421 UXT',
    namaSopir: 'Budi',
    kapasitas: '28',
    status: 'Aktif',
    kesiapan: 'Ready',
    keterangan: 'Siap muat',
    terakhirUpdate: '25 Sep 2026, 14:15 WIB',
  },
  {
    id: 'TRK-102',
    transporter: 'TM',
    depo: 'Karawang',
    nomorPolisi: 'B 9112 PE',
    namaSopir: 'Ahmad',
    kapasitas: '14',
    status: 'Aktif',
    kesiapan: 'Ready',
    keterangan: 'Standby pool',
    terakhirUpdate: '25 Sep 2026, 14:15 WIB',
  },
  {
    id: 'TRK-103',
    transporter: 'TM',
    depo: 'Baros',
    nomorPolisi: 'D 8203 YS',
    namaSopir: 'Joko',
    kapasitas: '8',
    status: 'Aktif',
    kesiapan: 'Ready',
    keterangan: 'Jadwal MD Karawang',
    terakhirUpdate: '25 Sep 2026, 14:15 WIB',
  },
  {
    id: 'TRK-104',
    transporter: 'TM',
    depo: 'Karawang',
    nomorPolisi: 'B 9772 KLP',
    namaSopir: 'Hendra',
    kapasitas: '20',
    status: 'Nonaktif',
    kesiapan: 'Tidak Ready',
    keterangan: 'Perbaikan transmisi di bengkel',
    terakhirUpdate: '25 Sep 2026, 11:30 WIB',
  },
  {
    id: 'TRK-105',
    transporter: 'TM',
    depo: 'Cirebon',
    nomorPolisi: 'B 9334 TAA',
    namaSopir: 'Slamet',
    kapasitas: '28',
    status: 'Aktif',
    kesiapan: 'Ready',
    keterangan: 'Siap kirim',
    terakhirUpdate: '25 Sep 2026, 14:15 WIB',
  },

  // Transporter RJTM (PT. Roda Jagat Tunas Mas)
  {
    id: 'TRK-201',
    transporter: 'RJTM',
    depo: 'Karawang',
    nomorPolisi: 'BM 8312 QU',
    namaSopir: 'Rian',
    kapasitas: '25',
    status: 'Aktif',
    kesiapan: 'Ready',
    keterangan: 'Siap jalan',
    terakhirUpdate: '25 Sep 2026, 13:40 WIB',
  },
  {
    id: 'TRK-202',
    transporter: 'RJTM',
    depo: 'Baros',
    nomorPolisi: 'BM 8004 AA',
    namaSopir: 'Eko',
    kapasitas: '14',
    status: 'Aktif',
    kesiapan: 'Ready',
    keterangan: 'Standby',
    terakhirUpdate: '25 Sep 2026, 13:40 WIB',
  },
  {
    id: 'TRK-203',
    transporter: 'RJTM',
    depo: 'Karawang',
    nomorPolisi: 'BM 8990 RT',
    namaSopir: 'Dedi',
    kapasitas: '28',
    status: 'Aktif',
    kesiapan: 'Ready',
    keterangan: 'Siap muat',
    terakhirUpdate: '25 Sep 2026, 13:40 WIB',
  },
  {
    id: 'TRK-204',
    transporter: 'RJTM',
    depo: 'Karawang',
    nomorPolisi: 'BK 9410 MN',
    namaSopir: 'Agus',
    kapasitas: '32',
    status: 'Nonaktif',
    kesiapan: 'Tidak Ready',
    keterangan: 'Sopir izin sakit',
    terakhirUpdate: '24 Sep 2026, 16:50 WIB',
  },
  {
    id: 'TRK-205',
    transporter: 'RJTM',
    depo: 'Cirebon',
    nomorPolisi: 'BM 8122 CC',
    namaSopir: 'Aris',
    kapasitas: '8',
    status: 'Aktif',
    kesiapan: 'Ready',
    keterangan: 'Standby garasi',
    terakhirUpdate: '25 Sep 2026, 13:40 WIB',
  },

  // Transporter WSS (PT. Wahana Sumber Sakti)
  {
    id: 'TRK-301',
    transporter: 'WSS',
    depo: 'Karawang',
    nomorPolisi: 'L 8821 UQ',
    namaSopir: 'Bambang',
    kapasitas: '28',
    status: 'Aktif',
    kesiapan: 'Ready',
    keterangan: 'Siap muat pagi',
    terakhirUpdate: '25 Sep 2026, 12:10 WIB',
  },
  {
    id: 'TRK-302',
    transporter: 'WSS',
    depo: 'Baros',
    nomorPolisi: 'L 9032 AB',
    namaSopir: 'Wahyu',
    kapasitas: '20',
    status: 'Aktif',
    kesiapan: 'Ready',
    keterangan: 'Siap kirim',
    terakhirUpdate: '25 Sep 2026, 12:10 WIB',
  },
  {
    id: 'TRK-303',
    transporter: 'WSS',
    depo: 'Karawang',
    nomorPolisi: 'N 8144 PK',
    namaSopir: 'Rudi',
    kapasitas: '14',
    status: 'Aktif',
    kesiapan: 'Ready',
    keterangan: 'Standby pool',
    terakhirUpdate: '25 Sep 2026, 12:10 WIB',
  },
  {
    id: 'TRK-304',
    transporter: 'WSS',
    depo: 'Karawang',
    nomorPolisi: 'L 9901 ZZ',
    namaSopir: 'Fikri',
    kapasitas: '8',
    status: 'Nonaktif',
    kesiapan: 'Tidak Ready',
    keterangan: 'Ganti ban dan kampas rem',
    terakhirUpdate: '24 Sep 2026, 15:20 WIB',
  },

  // Transporter SBR (PT. Sari Bumi Raya)
  {
    id: 'TRK-401',
    transporter: 'SBR',
    depo: 'Baros',
    nomorPolisi: 'B 9220 BKR',
    namaSopir: 'Sigit',
    kapasitas: '28',
    status: 'Aktif',
    kesiapan: 'Ready',
    keterangan: 'Siap muat',
    terakhirUpdate: '25 Sep 2026, 14:00 WIB',
  },
  {
    id: 'TRK-402',
    transporter: 'SBR',
    depo: 'Karawang',
    nomorPolisi: 'D 8991 AC',
    namaSopir: 'Deni',
    kapasitas: '8',
    status: 'Aktif',
    kesiapan: 'Ready',
    keterangan: 'Standby unit cadangan',
    terakhirUpdate: '25 Sep 2026, 14:00 WIB',
  },
  {
    id: 'TRK-403',
    transporter: 'SBR',
    depo: 'Baros',
    nomorPolisi: 'B 9553 SX',
    namaSopir: 'Ilham',
    kapasitas: '14',
    status: 'Aktif',
    kesiapan: 'Ready',
    keterangan: 'Siap kirim',
    terakhirUpdate: '25 Sep 2026, 14:00 WIB',
  },
  {
    id: 'TRK-404',
    transporter: 'SBR',
    depo: 'Karawang',
    nomorPolisi: 'D 8102 WQ',
    namaSopir: 'Wawan',
    kapasitas: '25',
    status: 'Nonaktif',
    kesiapan: 'Tidak Ready',
    keterangan: 'Perpanjangan uji KIR',
    terakhirUpdate: '25 Sep 2026, 09:15 WIB',
  },
];

export const TRANSPORTER_NAMES: Record<string, string> = {
  TM: 'PT. Tunas Muda',
  RJTM: 'PT. Roda Jagat Tunas Mas',
  WSS: 'PT. Wahana Sumber Sakti',
  SBR: 'PT. Sari Bumi Raya',
};

export const CAPACITY_OPTIONS = [
  '28',
  '25',
  '20',
  '14',
  '8',
  '4',
];
